Add grid to metadata grouping
yalelibrary/yul-dc-blacklight pull request #252
Opened 2020-08-28 02:18 UTC by K8Sewell

# Summary
Group metadata on single item show page into categories

# Related Ticket
#494 [ZenHub Link](https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/494)

# WIP Notes
* Needs better logic for inserting category titles because now it is dependent on the first metadata from that group to be present.  
* Needs styling

# Screenshots

![image](https://user-images.githubusercontent.com/36549923/91513670-c0c50880-e899-11ea-8193-044d2a16b743.png)
![image](https://user-images.githubusercontent.com/36549923/91513720-de926d80-e899-11ea-824e-182ecae6bd28.png)

2020-09-09 17:26 UTC, bess requested changes
@K8Sewell This is looking really good, and well done persevering with a challenging feature. I would like you to take so much logic out of the views, though. Generally speaking, we want to keep views as lightweight as possible, and avoid any significant logic happening there. If you're stuck on how to do that, let me know and let's pair on it.

2020-09-09 17:26 UTC, bess commented on app/controllers/catalog_controller.rb
> +    # Description Group
I like how you've added comments to group these together. It makes it easier to align with the presenter and the tests.

2020-09-09 17:26 UTC, bess commented on app/presenters/yul/description_metadata_presenter.rb
> +      @document = document.detect { |_i| Blacklight::ShowPresenter }[2].instance_variable_get("@document").to_h
I feel like there must be a more straightforward way of doing this, but I also remember what we saw when you were struggling with this. Maybe we could take a look together?

2020-09-09 17:26 UTC, bess commented on app/views/catalog/record/_identifier_metadata.html.erb
> +          <% end %>
This feels like a lot of logic to have in a view. Could we refactor this out into a helper method?

2020-09-09 17:26 UTC, bess commented on app/views/catalog/record/_keyword_metadata.html.erb
> +          <% end %>
Same here: I'd love to see this logic in a helper or somewhere it can be more easily unit tested.

2020-09-09 18:38 UTC, K8Sewell commented on app/controllers/catalog_controller.rb
> +    # Description Group
In the most recent commit I've pulled the logic from the view into a helper method.  Should help clean it up a fair bit.  Thank you for the comments!

2020-09-09 18:40 UTC, K8Sewell commented on app/presenters/yul/description_metadata_presenter.rb
> +      @document = document.detect { |_i| Blacklight::ShowPresenter }[2].instance_variable_get("@document").to_h
I'm unsure how to pull what we need to render the fields without this call.  Agree, it would be great to be more straightforward and I'd be happy to pair on it when you have time.

2020-09-10 17:51 UTC, bess approved these changes

2020-09-10 17:51 UTC, merged