742 accessibility updates
yalelibrary/yul-dc-blacklight pull request #370
Opened 2020-11-03 14:50 UTC by dl-maura

Co-authored-by: Martin Lovell <martin.lovell@yale.edu>

2020-11-04 19:31 UTC, alishaevn requested changes

2020-11-04 19:31 UTC, alishaevn commented on app/assets/stylesheets/customOverrides/show_page.scss
>    margin: 4px 4px 4px 0px;
![image](https://user-images.githubusercontent.com/29032869/98158051-313a6800-1e8f-11eb-9b7a-8e91f426a316.png)

the size of these buttons are off just a little bit. the width should be 160px and the height should be 44px. it's currently approx. 147x46.

2020-11-04 19:31 UTC, alishaevn commented on app/assets/stylesheets/customOverrides/advanced_search.scss
> +.adv-search-btn{
- these should have a font family of mallory_mp
- remove the hover effect
- make the outline a lighter grey

2020-11-04 19:31 UTC, alishaevn commented on app/assets/stylesheets/customOverrides/advanced_search.scss
> +  line-height: 38px;
```suggestion
    font-size: 20px;
    line-height: 16px;
    padding: 16px 25px;
    font-family: $mallory_mp
```

2020-11-04 19:31 UTC, alishaevn commented on app/assets/stylesheets/customOverrides/show_page.scss
>    margin: 4px 4px 4px 0px;
getting the padding exactly right per button is difficult because it seems to change on everyone one. so I would say as long as the "start over" and "back to search" buttons end up being the same height, and use the same `font size`, `line-height` and `padding` properties, that should be suffice.

2020-11-04 19:44 UTC, dl-maura commented on app/assets/stylesheets/customOverrides/advanced_search.scss
> +.adv-search-btn{
mallory_mp_medium?

2020-11-06 13:54 UTC, dl-maura commented
Martin tested this version so I'm going to change this to a regular PR for review

2020-11-09 22:46 UTC, alishaevn approved these changes

2020-11-10 13:26 UTC, merged