Link creator facet in show page
yalelibrary/yul-dc-blacklight pull request #372
Opened 2020-11-04 15:15 UTC by FCRodriguez7

Co-authored-by: Eric DeJesus <eric.dejesus@yale.com>

As a user, I want to be able to click on the creator name to get a search of the creator.
![Screen Shot 2020-11-03 at 1.02.52 PM.png](https://images.zenhubusercontent.com/5e6013c029e314c92afd4769/b8a0eb28-1eff-4d58-99fc-94cbfadef33e)

2020-11-04 17:16 UTC, maxkadel requested changes

2020-11-04 17:16 UTC, maxkadel commented on spec/system/view_fields_in_display_spec.rb
> +      creator_ssim: 'Eric',
Our tests will be most accurate if we use accurate stubs.

I would expect an ssim field to be an array, looking at my local solr:
```
"creator_ssim":["Bailey, William"],
"creator_tesim":["Bailey, William"],
```

If the test does not pass with this stub, we need to change either the field we're using, or how our code deals with that field.

2020-11-04 17:53 UTC, FCRodriguez7 commented on spec/system/view_fields_in_display_spec.rb
> +      creator_ssim: 'Eric',
I had the same concern. However, 'Erik & Frederick' is not reflective of the data in Solr. I have also added the branch to the test environment and is linked correctly.

2020-11-04 18:30 UTC, maxkadel commented on spec/system/view_fields_in_display_spec.rb
> +      creator_ssim: 'Eric',
I'm more concerned about array vs. string. What if you used ["Fredericks, Eric"] or something? 

I'm partly being strict about this because I think it's part of why the date slider tests were passing, but it wasn't working as expected in production. The values being stubbed in tests and those it was getting in production were very different.

2020-11-04 20:00 UTC, FCRodriguez7 commented on spec/system/view_fields_in_display_spec.rb
> +      creator_ssim: 'Eric',
I understand wanting the test data to look more like the data in Solr.  I was attempting to accomplish this with the test.   There are not an ampersand (&) in the creator Solr fields.  That was why I removed the &.  I was not trying to get a test to simply pass.   

The date slider test passing might be separate from this discussion.   The date slider data does not seem to be uniform causing some of the records to not appear.  Additionally,  the gem was buggy and there are records of the gem bugs in the date slider repo that no one knew about at the time it was implemented.

2020-11-04 20:32 UTC, maxkadel approved these changes

2020-11-04 20:47 UTC, FCRodriguez7 commented
I looked at the production environment there are a few records with &, for example  Cranston & Curtso.  &  %26

The code does not produce the expected outcome with records containing the & in the creator field.

2020-11-04 20:58 UTC, FCRodriguez7 commented
It also does not work for ' and "

2020-11-05 17:58 UTC, orangewolf commented on spec/system/view_fields_in_display_spec.rb
> +      creator_ssim: 'Eric',
I see both of these issues have been addressed. Good work here!

2020-11-05 17:59 UTC, orangewolf approved these changes

2020-11-05 17:59 UTC, merged