check authorization for PDFs
yalelibrary/yul-dc-blacklight pull request #416
Opened 2020-11-30 18:00 UTC by martinlovell

2020-11-30 18:01 UTC, martinlovell commented
Closing because already in progress by someone else.

2020-12-01 07:20 UTC, orangewolf approved these changes

2020-12-01 16:24 UTC, alishaevn requested changes

2020-12-01 16:24 UTC, alishaevn commented on app/controllers/concerns/check_authorization.rb
> +    404
shouldn't this be 401 for unauthorized? (like it is in the pdf controller)

2020-12-01 16:24 UTC, alishaevn commented on spec/requests/pdfs_request_spec.rb
> +      "title_tesim": ["[Map of China]. [yale-only copy]"],
I know this isn't what's being tested, but it's confusing to have a public work with "yale only copy" in the title.

2020-12-01 16:24 UTC, alishaevn commented on spec/requests/pdfs_request_spec.rb
> +      "title_tesim": ["[Map of China]. [yale-only copy]"],
same here as above.

2020-12-01 16:44 UTC, martinlovell commented on spec/requests/pdfs_request_spec.rb
> +      "title_tesim": ["[Map of China]. [yale-only copy]"],
Makes sense, updated

2020-12-01 16:44 UTC, martinlovell commented on spec/requests/pdfs_request_spec.rb
> +      "title_tesim": ["[Map of China]. [yale-only copy]"],
Updated here similarly

2020-12-01 16:54 UTC, martinlovell commented on app/controllers/concerns/check_authorization.rb
> +    404
I'm not sure.  The original code for manifests and image server is using 404, so I didn't want to change that with this PR. 
If manifests and images are ok with 401, we should do that for all of them.

2020-12-01 17:23 UTC, alishaevn commented on app/controllers/concerns/check_authorization.rb
> +    404
I did intend to go back and change the 404 on manifests to be 401. :)

2020-12-01 17:25 UTC, alishaevn commented on app/controllers/concerns/check_authorization.rb
> +    404
```suggestion
    401
```

2020-12-01 18:55 UTC, orangewolf approved these changes

2020-12-01 18:56 UTC, martinlovell commented on app/controllers/concerns/check_authorization.rb
> +    404
Updated PR so that manifests use CheckAuthorization module also.  Updated tests.
Setup CheckAuthorization to use same status code regardless of controller:
401 for anything that's not authorized, including if the document is found but has no visibility set.
404 for not found in SOLR.

2020-12-01 19:00 UTC, alishaevn approved these changes

2020-12-01 19:00 UTC, merged