I708 iiif image auth
yalelibrary/yul-dc-blacklight pull request #420
Opened 2020-11-30 20:21 UTC by maxkadel

Reverted previous PR since it was not deployable (yet). Working on a camerata PR that should hopefully make it deployable.

https://github.com/yalelibrary/yul-dc-blacklight/pull/419

2020-11-30 20:25 UTC, mlooney requested changes

2020-11-30 20:25 UTC, mlooney commented on ops/webapp.conf
> +        proxy_pass http://127.0.0.1:3000/check-iiif; # Send the user access request to the API server
backend doesn't live on localhost anymore. $cluster_name.images.$cluster_name should do it

2020-11-30 20:28 UTC, mlooney commented on ops/webapp.conf
> +        proxy_pass http://127.0.0.1:3000/check-iiif; # Send the user access request to the API server
oops, it's actually thus: $cluster_name-images.$cluster_name

2020-12-01 07:22 UTC, orangewolf commented on ops/webapp.conf
> +        proxy_pass http://127.0.0.1:3000/check-iiif; # Send the user access request to the API server
not even within the container? this is only an internal call (nginx is running in this container)

2020-12-01 14:57 UTC, maxkadel commented on ops/webapp.conf
> +        proxy_pass http://127.0.0.1:3000/check-iiif; # Send the user access request to the API server
@orangewolf  - Did you see the comment on the revert? Tried deploying this code and got message below, and the app wouldn't start up at all. I'll try deploying this branch to test today and see if this works. I'm not sure I understand the proxying yet, though, so I'm not sure how successful I'll be.

![image](https://user-images.githubusercontent.com/45948126/100756653-703ed900-33bb-11eb-95a9-24dfe3165466.png)

2020-12-01 18:09 UTC, mlooney approved these changes

2020-12-01 18:57 UTC, orangewolf commented on ops/webapp.conf
> +        proxy_pass http://127.0.0.1:3000/check-iiif; # Send the user access request to the API server
sure max, but that isn't related to this line, its related to the one below that you changed =-)

2020-12-01 20:46 UTC, maxkadel commented
Closing in favor of resolved PR - https://github.com/yalelibrary/yul-dc-blacklight/pull/425

2020-12-01 20:46 UTC, closed without merging