Publication date
yalelibrary/yul-dc-blacklight pull request #426
Opened 2020-12-01 21:43 UTC by MaggieZhaoYale

2020-12-01 22:04 UTC, maxkadel requested changes
If you would put back the "Extent of Digitization" change I think the other work looks good.

2020-12-01 22:04 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_facet_field 'extentOfDigitization_ssim', label: 'Extent of Digitizations', limit: true
Was this requested in the ticket? I think it's unrelated to the other work, and I'm not positive it's correct.

2020-12-02 13:47 UTC, MaggieZhaoYale reviewed
> If you would put back the "Extent of Digitization" change I think the other work looks good.

Thank you @maxkadel  I put back the  "Extent of Digitization"

2020-12-02 14:27 UTC, maxkadel requested changes

2020-12-02 14:27 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_index_field 'dateStructured_ssim', label: 'Date Created', highlight: true, solr_params: disp_highlight_on_search_params
On second thought, I don't *think* we want to add this here. I think we want to change the label for `date_ssim` (currently on line 147) to "Published / Created" (need to add the space between the slash so that a screen reader can read it more easily). 

If, from your work with the metadata task force, you know that it should use the dateStructured field, I think we still need the label change and it should replace the current `date_ssim`, rather than be in addition to it.

2020-12-02 15:28 UTC, maxkadel approved these changes

2020-12-02 15:54 UTC, merged