Common fields -> All fields
yalelibrary/yul-dc-blacklight pull request #429
Opened 2020-12-02 22:57 UTC by alishaevn

# Ticket
https://app.zenhub.com/workspaces/yul-dc-5e50083561915b11fc9e5850/issues/yalelibrary/yul-dc/735

# Summary
- The first option on a basic search is "All Fields"
- That option will do a search on all fields instead of a preset list
- The "All Fields" option on advanced search will behave the same way

# Demo
Before: https://share.getcloudapp.com/WnulNzY8
After: https://share.getcloudapp.com/2Nu0B1Dr

2020-12-02 22:58 UTC, alishaevn commented on app/controllers/catalog_controller.rb
> -    end
all of this is unnecessary because of un-commenting line 252

2020-12-02 23:00 UTC, alishaevn commented on app/controllers/catalog_controller.rb
> -    end
after un-commenting line 252, this code made it to where there were 2 "All Fields" search boxes on the advanced search page.

having line 252 alone seems to work fine. unless there's a reason that the "all fields" search option on advanced search needs to be filtered??

2020-12-03 02:28 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_search_field 'all_fields', label: 'All Fields'
So, my understanding is that we don't want to *actually* search all the fields, only search the fields that were previously called "Common fields", and just change the label.

The question about the duplicate "all fields" on the advanced search is good - how do we indicate "all fields" then "no really, this one is *all* the fields." I wonder whether we could include the advanced search "all fields" in the simple search, but have it default to something like "Common Fields" or try out a different name. 

The reason we don't want to default to *actually* searching all the fields is that it's likely to bring up a lot of false positives for most searches for most users. Some of the fields included in advanced search "all fields" are administrative. So, if I'm a regular user and I want to find things in the collection for "Rights" (don't ask me why that's my search term), I don't want to see all the access restrictions that include the word "Rights," I want to see content that relates to rights. But, if I'm a librarian using advanced search, I might want to search for that kind of thing.

2020-12-03 02:28 UTC, maxkadel requested changes
I don't think we want to take out the current search functionality, just change labels.

2020-12-03 02:29 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_search_field 'all_fields', label: 'All Fields'
Thought - maybe we could call the advanced search flavor of "all fields" "Extended field search" or something?

2020-12-03 16:56 UTC, alishaevn commented on app/controllers/catalog_controller.rb
> +    config.add_search_field 'all_fields', label: 'All Fields'
@maxkadel the ticket says to change the label _and_ function to be "all fields", so that's why I did it that way. I did also think about simply renaming the field on the advanced search since it's actually a search of only certain fields. although it's a longer list than what was previously selected in the "common fields".

if we want the "all fields" on basic search to be more than "common fields" but less than a true "all fields", I'll need that list. assuming, according to your reasoning above, that it's not the same as the `advanced_search_fields` in the deleted section above.

@mark-dce @orangewolf thoughts?

2020-12-03 18:10 UTC, alishaevn commented on app/controllers/catalog_controller.rb
> +    config.add_search_field 'all_fields', label: 'All Fields'
per rebecca hirsch in slack "I would prefer it mirror the functionality of the advanced search “all fields”"

2020-12-04 14:21 UTC, maxkadel approved these changes

2020-12-04 14:22 UTC, maxkadel commented
> I don't think we want to take out the current search functionality, just change labels.

I was wrong! Got confirmation from Maura and Rebecca that the "all fields" search should match the old advanced search "all fields" search.

2020-12-04 14:22 UTC, merged