888 update blacklight depreciated solr fields mc101
yalelibrary/yul-dc-blacklight pull request #431
Opened 2020-12-03 22:09 UTC by FCRodriguez7

- [ ] abstract_ssim: json_to_index["abstract"], # replaced by abstract_tesim
- [ ] alternativeTitle_ssim: json_to_index["alternativeTitle"], # replaced by alternativeTitle_tesim
- [ ] box_ssim: extract_container_information(json_to_index), # replaced by containerGrouping
- [ ] date_tsim: json_to_index["date"], # replaced by dateStructured_ssim
- [ ] identifierShelfMark_ssim: json_to_index["callNumber"], # replaced by callNumber_ssim
- [ ] identifierShelfMark_tesim: json_to_index["callNumber"], # replaced by callNumber_tesim
- [ ] oid_ssim: oid, # replaced by oid_ssi
- [ ] geo_subject_ssim: json_to_index["geoSubject"], # replaced by geoSubject_ssim
- [ ] material_ssim: json_to_index["material"], # replaced by material_tesim
- [ ] orbisBarcode_ssim: json_to_index["orbisBarcode"] || json_to_index["barcode"], # replaced by orbisBarcode_ssi
- [ ] orbisBibId_ssim: json_to_index["orbisBibId"], # replaced by orbisBibId_ssi
- [ ] projection_ssim: json_to_index["projection"], # replaced by projection_tesim
- [ ] publicationPlace_ssim: json_to_index["creationPlace"], #replaced by creationPlace_ssim
- [ ] publicationPlace_tesim: json_to_index["creationPlace"],#replaced by creationPlace_tesim
- [ ] recordType_ssim: json_to_index["recordType"], # replaced by recordType_ssi
- [ ] references_ssim: json_to_index["preferredCitation"], # replaced by references_tesim
- [ ] references_tesim: json_to_index["preferredCitation"], # replaced by preferredCitation_tesim
- [ ] scale_ssim: json_to_index["scale"], # replaced by scale_tesim
- [ ] sourceCreated_ssim: json_to_index["sourceCreated"], # replaced by sourceCreated_tesim
- [ ] sourceDate_ssim: json_to_index["sourceDate"], # replaced by sourceDate_tesim
- [ ] sourceEdition_ssim: json_to_index["sourceEdition"], # replaced by sourceEdition_tesim
- [ ] sourceNote_ssim: json_to_index["sourceNote"], # replaced by sourceNote_tesim
- [ ] sourceTitle_ssim: json_to_index["sourceTitle"], # repleaced by sourceTitle_tesim
- [ ] subject_topic_tsim: json_to_index["subjectTopic"], # replaced by subjectTopic_tesim and subjectTopic_ssim
- [ ] title_tsim: json_to_index["title"] # replaced by title_tesim

----

- [ ] when work is finished do a re-index before deploying (update metadata, not just solr re-index)
   - [ ] test
   - [ ] infra
   - [ ] uat
   - [ ] demo
   - [ ] staging
   - [ ] production

----
- [ ] Check with Maura
   - [ ] partOf_tesim: json_to_index["partOf"], check with Maura 
   - [ ] partOf_ssim: json_to_index["partOf"], check with Maura 

---

2020-12-15 19:48 UTC, maxkadel requested changes
I'm not convinced that this is the best approach - I think keeping solr field names & metadata cloud field names consistent across 3 repositories is going to be very labor intensive without a lot of immediate value (as far as I know), and with the risk of being breaking if not carefully coordinated with reindexes. 

That said, if this is the decision, please:
- [ ] Separate the date field changes into a separate PR and link them to a ticket specifically referencing them
- [ ] Fix `subjecttitle_tesim` to be either snake or camel case consistently throughout. If it's wrong in Management, make a ticket to fix it.

2020-12-15 19:48 UTC, maxkadel commented on spec/support/solr_documents/advanced_search_testing_only.rb
> +  "subjecttitle_tesim": ["Islamic binding"],
This should probably be either camel case or snake case?

2020-12-15 19:48 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +      'subjecttitle_tesim',
should probably be either camel case or snake case (repeated throughout)

2020-12-15 19:48 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_index_field 'dateStructured_ssim', label: 'Published / Created', highlight: true
Are we sure we want this field showing on the index page? I think, if so, we should do it as a separate PR since dates have been such a complicated issue

2020-12-15 19:48 UTC, maxkadel commented on app/controllers/catalog_controller.rb
> +    config.add_show_field 'dateStructured_ssim', label: 'Published / Created', metadata: 'origin'
Are we sure we want this field showing on the show page? I think, if so, we should do it as a separate PR since dates have been such a complicated issue

2020-12-15 20:42 UTC, orangewolf commented
> I'm not convinced that this is the best approach - I think keeping solr field names & metadata cloud field names consistent across 3 repositories is going to be very labor intensive without a lot of immediate value (as far as I know), and with the risk of being breaking if not carefully coordinated with reindexes.
> 
> That said, if this is the decision, please:
> 
> * [ ]  Separate the date field changes into a separate PR and link them to a ticket specifically referencing them
> * [ ]  Fix `subjecttitle_tesim` to be either snake or camel case consistently throughout. If it's wrong in Management, make a ticket to fix it.

@maxkadel I think that planning the ticket is the right place to talk about this and we decided to wait architecturally on a more comprehensive solution. I don think your secondary points are good ones =-)

2020-12-15 22:00 UTC, FCRodriguez7 commented on app/controllers/catalog_controller.rb
> +      'subjecttitle_tesim',
I will double-check on this field.

2020-12-17 00:40 UTC, maxkadel approved these changes

2020-12-17 05:55 UTC, merged