943 refactor visibility checks hide private metadata
yalelibrary/yul-dc-blacklight pull request #457
Opened 2020-12-21 16:42 UTC by martinlovell

Hides metadata for items with private or unknown visibility.
Refactors access checking code to consolidate.
Adds helper for restriction information displayed to user when digital is restricted or digital/metadata is restricted.

2020-12-21 17:45 UTC, maxkadel requested changes
Looks awesome - one requested change on more explanation for method / possible re-name - see comments.

2020-12-21 17:45 UTC, maxkadel commented on app/models/search_builder.rb
>    def show_only_public_records(solr_parameters)
Are we still using the `public_b` field? 

[Requested change]: 
I'm not totally clear on this method, could you add more comments to explain it? 

It seems like it's adding both "Public" and "Yale Community Only" visibilities, so maybe we need to find a word other than "Public" for the method name?

2020-12-21 17:45 UTC, maxkadel commented on app/helpers/access_helper.rb
> +# frozen_string_literal: true
I like this refactor, I think it's nice to have this in a single helper module

2020-12-21 17:45 UTC, maxkadel commented on README.md
> +By default, when running locally, your IP will not be considered "On Campus," so you will not be able to view Yale Community Only items unless you log in.
I like this explanation a lot - could we link to it / refer to it from where folks will be testing as well? (in the tests themselves?)

2020-12-21 18:35 UTC, martinlovell commented on app/models/search_builder.rb
>    def show_only_public_records(solr_parameters)
Renamed it to filter_by_visibility and updated comment.  (It doesn't look like the public_bsi is used anywhere except in some specs.)

2020-12-21 18:41 UTC, martinlovell commented on README.md
> +By default, when running locally, your IP will not be considered "On Campus," so you will not be able to view Yale Community Only items unless you log in.
I added a comment to access_restrictions_spec.rb.  (Let me know if there's a better way to format the comment so that it's easier to view the README.  I could use the full URL to the README on github.)

2020-12-22 16:01 UTC, maxkadel approved these changes

2020-12-22 16:01 UTC, merged