add type="text" to the languageTerm
yalelibrary/yul-dc-blacklight pull request #511
Opened 2021-04-13 22:39 UTC by dylansalay

2021-04-13 23:27 UTC, alishaevn approved these changes

2021-04-15 18:04 UTC, FCRodriguez7 approved these changes

2021-04-15 19:32 UTC, mikeapp requested changes

2021-04-15 19:32 UTC, mikeapp commented on app/models/concerns/mods_solr_document.rb
> +          xml['mods'].languageTerm({ type: "text" })
I see this PR is being approved even though it is in draft, so I thought I'd comment.  The current code generates an empty `languageTerm`:
```
<mods:languageTerm type="text" ></mods:languageTerm>
<mods:language>
<mods:languageTerm>Arabic</mods:languageTerm>
</mods:language>
```
but the desired output is:
```
<mods:language>
<mods:languageTerm  type="text">Arabic</mods:languageTerm>
</mods:language>
```

2021-04-20 13:56 UTC, MaggieZhaoYale commented on app/models/concerns/mods_solr_document.rb
> +          xml['mods'].languageTerm({ type: "text" })
<img width="912" alt="Screen Shot 2021-04-20 at 9 56 26 AM" src="https://user-images.githubusercontent.com/46331329/115408220-b0fa8b80-a1be-11eb-90da-f52592d20d9d.png">

2021-04-20 18:35 UTC, martinlovell approved these changes

2021-04-20 18:37 UTC, mikeapp approved these changes

2021-04-20 18:37 UTC, merged