add checkout box for Full text on search bar
yalelibrary/yul-dc-blacklight pull request #575
Opened 2021-06-11 15:48 UTC by MaggieZhaoYale

2021-06-11 17:12 UTC, FCRodriguez7 requested changes
The pr needs a test.

2021-06-11 18:06 UTC, mlooney submitted a review, later dismissed

2021-06-11 19:11 UTC, MaggieZhaoYale commented
Need to add full text to simple search drop down and advanced search field too

2021-06-21 12:29 UTC, MaggieZhaoYale commented
close this one

2021-06-21 12:29 UTC, closed without merging