2653 parent object page owp
yalelibrary/yul-dc-blacklight pull request #944
Opened 2023-11-06 21:31 UTC by jpengst

2023-11-08 14:39 UTC, mikeapp requested changes

2023-11-08 14:39 UTC, mikeapp commented on app/views/catalog/_show_main_content.html.erb
> +    <% elsif !client_can_view_owp?(@document) && current_user %>
Does this need to prepend the check `object_owp?(@document) && ...` ?  It seems like this will return false if the user is logged in even if the document _ isn't_ OwP.   

With non-Yale users there should be a case where the user is logged in and they do not have access to Yale content, which seems to be the case handled by the final `else` in line 29.

2023-11-08 16:59 UTC, mikeapp commented on app/helpers/access_helper.rb
> +    url = URI.parse("#{ENV['MANAGEMENT_HOST']}/api/permission_sets/#{current_user.sub}") if current_user
Should the `if` wrap the entire call?  Otherwise `url` is nil in the following line?

2023-11-08 17:01 UTC, mikeapp commented on app/helpers/access_helper.rb
> +  def retrieve_user_permissions
The user permissions are going to need to be cached in the user's session at login rather than retrieved via API with every check.

2023-11-08 17:30 UTC, jpengst commented on app/views/catalog/_show_main_content.html.erb
> +    <% elsif !client_can_view_owp?(@document) && current_user %>
Excellent catch. Definitely needed the extra `object_owp?(@document)` on that line. Confirmed that this is now working and I'm able to access the non-Yale users restriction message

2023-11-08 17:32 UTC, jpengst commented on app/helpers/access_helper.rb
> +    url = URI.parse("#{ENV['MANAGEMENT_HOST']}/api/permission_sets/#{current_user.sub}") if current_user
Correct. The current_user check here is redundant since the method can't be called without a current_user. I think I wrote that conditional before I had the front end checks in place.

2023-11-13 18:15 UTC, mikeapp commented on app/helpers/access_helper.rb
> +  def owp_restriction_message(document)
Is this used anywhere?

2023-11-13 18:17 UTC, mikeapp requested changes

2023-11-13 18:17 UTC, mikeapp commented on app/helpers/access_helper.rb
> +  def object_owp?(document)
Can this be used in line 22 above instead of the `==` check?

2023-11-14 14:22 UTC, mikeapp requested changes

2023-11-14 14:22 UTC, mikeapp commented on app/views/catalog/_show_main_content.html.erb
> +<%= render 'show_tools' unless object_owp?(@document) && !client_can_view_owp?(@document) %>
Can we leave the original version here?   I think the check in the show_tools partial will cause the digital links to be disabled.  It would still leave the `Cite` option.

2023-11-15 15:25 UTC, mikeapp approved these changes

2023-11-15 15:25 UTC, merged