Add terms and conditions to show page
yalelibrary/yul-dc-blacklight pull request #984
Opened 2024-03-06 22:40 UTC by K8Sewell

# Summary
Adds the terms and conditions for an open with permission object to the show page, just under the rights statement, with truncation toggle for long text.

# Related Ticket
[#2745](https://github.com/yalelibrary/YUL-DC/issues/2745)

# Screenshot
![image](https://github.com/yalelibrary/yul-dc-blacklight/assets/36549923/73218eff-bbb4-4238-a561-b311facf9701)

2024-03-12 18:14 UTC, mikeapp requested changes

2024-03-12 18:14 UTC, mikeapp commented on app/views/catalog/_grouped_metadata.html.erb
> +      console.log('it is shorter than really is')
Please remove this and the log below.

2024-03-12 18:53 UTC, K8Sewell commented on app/views/catalog/_grouped_metadata.html.erb
> +      console.log('it is shorter than really is')
Thanks for catching this!  The console logs were removed in the most recent commit.

2024-03-13 15:35 UTC, mikeapp approved these changes

2024-03-13 15:35 UTC, merged